FROM ghcr.io/bjia56/armv7l-wheel-builder:main

RUN go install github.com/go-python/gopy@v0.4.5 && \
    go install golang.org/x/tools/cmd/goimports@latest

RUN mkdir build
WORKDIR build
COPY . .

RUN ./scripts/armv7l_build_wheels.sh

RUN mkdir /export && \
    cp build3.7/wheelhouse/*.whl /export && \
    cp build3.8/wheelhouse/*.whl /export && \
    cp build3.9/wheelhouse/*.whl /export && \
    cp build3.10/wheelhouse/*.whl /export && \
    cp build3.11/wheelhouse/*.whl /export
