name: Build and publish wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag version'
        required: true
        type: string
      description:
        description: 'Release description'
        required: true
        type: string
      create-release:
        description: 'Actually creates and publishes the release'
        required: true
        type: boolean
        default: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-args:
    runs-on: ubuntu-latest
    steps:
      - name: Print input arguments
        run: echo "${{ toJSON(github.event.inputs) }}"

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ inputs.version }}

      - uses: nick-fields/assert-action@v2
        with:
          expected: "false"
          actual: "${{ steps.check-tag.outputs.exists }}"
          comparison: exact

  build:
    needs: validate-args
    uses: ./.github/workflows/build_wheel.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: /tmp/wheelhouse/
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ inputs.create-release }}
        with:
          files: /tmp/wheelhouse/*.whl
          tag_name: ${{ inputs.version }}
          body: ${{ inputs.description }}

  update-pypi:
    if: ${{ inputs.create-release }}
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull latest
        run: |
          git pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Update PyPI
        run: python ./scripts/generate_pypi_links.py ${{ inputs.version }}

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          commit_message: Update PyPI

  publish-pypi:
    needs: update-pypi
    uses: ./.github/workflows/pages.yml
